import Head from "next/head";

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import {
  query,
  where,
  setDoc,
  doc,
  collection,
  getFirestore,
  getDocs,
} from "firebase/firestore";
import {
  User,
  getAuth,
  signInWithPopup,
  GoogleAuthProvider,
} from "firebase/auth";

import { useAuthState } from "react-firebase-hooks/auth";
import { useCollectionData, useDocument } from "react-firebase-hooks/firestore";
import { ChatScreen } from "../components/screens/chat-screen";
import { auth, db } from "../components/firebase";
import { GroupScreen } from "../components/screens/group-screen";
import { SignInScreen } from "../components/screens/signin-screen";

export default function Home() {
  const [user] = useAuthState(auth);

  if (!user) {
    return <SignInScreen />;
  } else {
    return <GroupScreen />;
  }
  // return (
  //   <div>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <ChatScreen />
  //   </div>
  // );
}
